package Extensions.Platforms.LocalExecutionPlatform.GUI;

import Core.CommandLine.MainInterpreter;
import Core.CommandLine.Platforms.PlatformMessage;
import Extensions.Platforms.LocalExecutionPlatformHeader;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class LocalClient {

    private static int clientCounter = 0;

    private JTextArea textArea1;
    private JPanel panel1;
    private JTextPane textPane1;
    private String clientID;

    private LocalClient() {

        clientID = "localExecutionPlatformClient" + (++clientCounter);
        textArea1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    MessageSend(textArea1.getText());
                    textArea1.setText("");
                }
            }
        });
    }

    private void MessageSend(String s) {
        LocalExecutionPlatformHeader header = new LocalExecutionPlatformHeader(this);
        header.setUserIdentifier(clientID);
        PlatformMessage message = new PlatformMessage();
        message.SetHeader(header);
        message.SetMessage(s);
        MainInterpreter.HandleMessage(message);
    }

    public void ReceiveMessage(String s) {
        textPane1.setText(textPane1.getText() + s + "\n");
    }

    public static void CreateClients(int numberOfClients)
    {
        for(int i=1;i<=numberOfClients;i++)
        {
            JFrame frame = new JFrame("LocalClient" + i);
            frame.setContentPane(new LocalClient().panel1);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setMinimumSize(new Dimension(1024,768));
            frame.pack();
            frame.setVisible(true);
        }
    }

    public static void main(String[] args) {

        int n = 1;

        if(args.length > 0)
        {
            n = Integer.parseInt(args[0]);
        }

        CreateClients(n);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        textArea1 = new JTextArea();
        textArea1.setBackground(new Color(0xCCCCD4));
        panel1.add(textArea1, BorderLayout.SOUTH);
        textPane1 = new JTextPane();
        panel1.add(textPane1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
